version: "3.9"

services:
  web:
    container_name: cyber_store
    image: cyber-store:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL:-http://127.0.0.1:8000/}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY:-6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI}
    ports:
      - "3000:3000" # HOST:CONTAINER
    # Next.js NEXT_PUBLIC_* variables are evaluated at build-time.
    # Ensure .env.production has correct values before building.
    env_file:
      - .env.production
    environment:
      # Runtime vars for the Next.js standalone server
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      NEXT_TELEMETRY_DISABLED: "1"
      # These allow overriding at runtime if your app reads them on the server side.
      # Note: for browser code, NEXT_PUBLIC_* values are baked in at build time from .env.production.
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL:-http://127.0.0.1:8000/}
      NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY:-6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI}
      # Server-side (inside container) base URL to reach your backend running on HOST
      # For Mac/Windows Docker: host.docker.internal resolves to host machine
      NEXT_INTERNAL_API_BASE_URL: ${NEXT_INTERNAL_API_BASE_URL:-http://host.docker.internal:8000/}
    restart: unless-stopped
